site_name: COMP423 Course Notes
theme:
  name: material
  features: 
  - content.code.copy
  - content.code.select
  - content.code.annotate
  icon: 
    admonitition: 
      note: octicons/tag-16
      question: octicons/question-16
      warning: octicons/alert-16
      
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true